# Generated by Django 5.0.3 on 2024-03-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient_name',
        ),
    ]
